(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "cask")
(depends-on "elpy")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "pallet")
(depends-on "python-mode")
(depends-on "python-pep8")
(depends-on "python-pylint")
(depends-on "yasnippet")