(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "browse-kill-ring+")
(depends-on "cask")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "elpy")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "psgml")
(depends-on "python-pep8")
(depends-on "python-pylint")
(depends-on "magit")

(depends-on "auctex")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "ggtags")

;; File mode
(depends-on "python-mode")
(depends-on "apache-mode")
(depends-on "go-mode")
(depends-on "yaml-mode")
