
(defun encapsulate-glossary ()
    "Toggle setting tab widths between 4 and 8"
    (interactive)
	(setq startp nil)
	(setq endp nil)
	(if (use-region-p)
		;;(message "there is a text selection: %s" to-replace)
		(let ((selection (buffer-substring-no-properties (region-beginning) (region-end))))
		  (if (= (length selection) 0)
			  (message "empty string")
			(progn ; there is a text selection
			  (setq startp (region-beginning))
			  (setq endp (region-end))
			  ))
		  )
	  )
	(if (eq startp nil)
		(progn
		  (forward-word)
		  (setq endp (point))
		  (backward-word)
		  (setq startp (point))))
	(kill-ring-save startp endp)
	(let ((to-replace (buffer-substring-no-properties startp endp)))
	  (setq replacement (concat "\\gls{" to-replace "}"))
	  ;;(message "to-replace: %s, replacement: %s" to-replace replacement)
	  (goto-char startp)
	  (query-replace to-replace replacement)
	  ))
