;; This cask files is a limited version of the main Cask file
(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "cask")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "pallet")
(depends-on "yasnippet")
(depends-on "editorconfig")

;; Utils
(depends-on "ggtags" :git "https://github.com/leoliu/ggtags" :ref "0.8.13")
(depends-on "xclip")
(depends-on "exec-path-from-shell")
(depends-on "visual-regexp")

;; File mode
(depends-on "apache-mode")
(depends-on "go-mode")
(depends-on "yaml-mode")
(depends-on "psgml") ;; XML, HTML, markup langs ++
(depends-on "dockerfile-mode")
(depends-on "jinja2-mode")

;; Python
(depends-on "python-mode")
(depends-on "python-pep8" :git "https://github.com/emacsmirror/python-pep8")
(depends-on "python-pylint" :git "https://github.com/emacsmirror/python-pylint")

;; LaTeX
(depends-on "auctex")
(depends-on "auto-complete")
